name: amigatoy
description: Amigatoy Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  firebase_core: ^0.4.5  # add dependency for Firebase Core
#  firebase_analytics: 5.0.2
#  firebase_database: 3.0.6
#  cloud_firestore: 0.13.7
#  firebase_auth: ^0.14.0+5
  rxdart: ^0.27.1
#  bloc: ^3.0.0
  flutter_bloc: ^7.0.1
  equatable: ^2.0.2
  parse_server_sdk: ^3.0.0
  http: ^0.13.3
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  flutter_html: ^2.1.0
#item repository
#  firebase_repository:
#    path: firebase_repository



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  random_pk: any
  shimmer: ^2.0.0
  transparent_image: ^2.0.0
  flutter_slidable: ^0.6.0
#  flutter_rating: ^0.0.2
  change_app_package_name: ^1.0.0
  formz: ^0.4.0
  email_validator: ^2.0.1
  intl: ^0.17.0
#  formz: ^0.4.0



dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Sans
      fonts:
        - asset: assets/font/OpenSans-Bold.ttf
          weight: 800
        - asset: assets/font/OpenSans-Semibold.ttf
          weight: 600
        - asset: assets/font/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/font/OpenSans-Light.ttf
          weight: 200
    - family : Popins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-SemiBold.ttf
          weight : 600
    - family : Berlin
      fonts:
        - asset: assets/font/BRLNSDB.TTF
          weight: 700
    - family : Gotik
      fonts:
        - asset: assets/font/GOTHIC.TTF
          weight: 400
        - asset: assets/font/GOTHICB.TTF
          weight : 600

  assets:
    - assets/img/google.png
    - assets/img/googlewallet.png
    - assets/img/credit.png
    - assets/img/handshake.png
    - assets/img/paypal.png
    - assets/img/icon_facebook.png
    - assets/img/Logo.png
    - assets/img/Rectangle.png
    - assets/img/girl.png
    - assets/img/loginscreenbackground.png
    - assets/img/backgroundgirl.png
    - assets/img/man.png
    - assets/img/search.png
    - assets/img/search2.png
    - assets/img/chat.png
    - assets/img/notifications-button.png
    - assets/img/baner1.png
    - assets/img/baner2.png
    - assets/img/baner3.png
    - assets/img/baner4.png
    - assets/img/baner12.png
#    - assets/icon/book.png
    - assets/icon/addwish.png
    - assets/icon/wishsuccess.png
    - assets/icon/camera.png
    - assets/icon/fashion.png
    - assets/icon/food.png
    - assets/icon/game.png
    - assets/icon/handphone.png
    - assets/icon/health.png
    - assets/icon/mesin.png
    - assets/icon/otomotif.png
    - assets/icon/pc.png
    - assets/icon/sport.png
    - assets/icon/ticket.png
    - assets/imgPromo/Discount1.png
    - assets/imgPromo/Discount2.png
    - assets/imgPromo/Discount3.png
    - assets/imgPromo/Discount4.png
    - assets/imgPromo/Discount5.png
    - assets/imgPromo/Discount6.png
    - assets/img/flashsaleicon.png
    - assets/imgItem/mackbook.jpg
    - assets/imgItem/fashion1.jpg
    - assets/imgItem/flashsale2.jpg
    - assets/imgItem/flashsale3.jpg
    - assets/imgItem/flashsale4.jpg
    - assets/imgItem/flashsale5.jpg
    - assets/imgItem/category1.png
    - assets/imgItem/category2.png
    - assets/imgItem/category3.png
    - assets/imgItem/category4.png
    - assets/imgItem/category5.png
    - assets/imgItem/category6.png
    - assets/imgItem/category7.png
    - assets/imgItem/category8.png
    - assets/imgItem/acesoris1.jpg
    - assets/imgItem/beauty1.jpg
    - assets/imgItem/girl1.jpg
    - assets/imgItem/kids1.jpg
    - assets/imgItem/man1.jpg
    - assets/imgItem/shoes1.jpg
    - assets/imgItem/shoes2.jpg
    - assets/img/notmessage.png
    - assets/img/noNotification.png
    - assets/imgBrand/appleHeader.png
    - assets/imgBrand/fendiHeader.png
    - assets/imgBrand/gucciHeader.png
    - assets/imgBrand/nikeHeader.png
    - assets/imgBrand/samsungHeader.png
    - assets/imgBrand/sonyHeader.png
    - assets/img/womanface.jpg
    - assets/icon/truck.png
    - assets/icon/chat.png
    - assets/icon/notification.png
    - assets/icon/callcenter.png
    - assets/icon/setting.png
    - assets/icon/aboutapp.png
    - assets/icon/shopping-cart.png
    - assets/icon/message.png
    - assets/img/bannerMan1.png
    - assets/img/bannerMan2.png
    - assets/img/bannerMan3.png
    - assets/img/bannerMan4.png
    - assets/imgCamera/CameraDigital.png
    - assets/imgCamera/CompactCamera.png
    - assets/imgCamera/ActionCamera.png
    - assets/imgCamera/cameraItem1.png
    - assets/imgCamera/cameraItem2.png
    - assets/imgCamera/cameraItem3.png
    - assets/imgCamera/cameraItem4.png
    - assets/imgPromo/imgPromo1.jpg
    - assets/imgPromo/imgPromo2.jpg
    - assets/imgPromo/imgPromo3.jpg
    - assets/imgPromo/imgPromo4.jpg
    - assets/imgPromo/imgPromo5.jpg
    - assets/imgPromo/imgPromo6.jpg
    - assets/imgPromo/imgPromo7.jpg
    - assets/imgPromo/imgPromo8.jpg
    - assets/imgCategoryMan/Man1.jpg
    - assets/imgCategoryMan/Man2.jpg
    - assets/imgCategoryMan/Man3.jpg
    - assets/imgCategoryMan/Man4.jpg
    - assets/imgCategoryMan/Man5.jpg
    - assets/imgCategoryMan/Man6.jpg
    - assets/img/bag.png
    - assets/img/courier.png
    - assets/img/house.png
    - assets/img/order.png
    - assets/img/payment.png
    - assets/icon/girlcallcenter.png
    - assets/img/checklist.png
    - assets/icon/creditAcount.png
    - assets/img/creditCardVisa.png
    - assets/imgBrand/brandNike.jpg
    - assets/imgBrand/brandApple.jpg
    - assets/img/flashsalebanner.png
    - assets/icon/flashSaleIcon.png
    - assets/img/headerProfile.png
    - assets/img/SliderLogin2.png
    - assets/img/SliderLogin3.png
    - assets/img/SliderLogin4.png
    - assets/imgIllustration/IlustrasiMessage.png
    - assets/imgIllustration/IlustrasiOnBoarding1.png
    - assets/imgIllustration/IlustrasiOnBoarding2.png
    - assets/imgIllustration/IlustrasiOnBoarding3.png
    - assets/avatars/avatar-1.jpg
    - assets/avatars/avatar-2.jpg
    - assets/avatars/avatar-3.jpg
    - assets/avatars/avatar-4.jpg
    - assets/avatars/avatar-5.jpg
    - assets/avatars/avatar-6.jpg
    - assets/imgIllustration/IlustrasiCart.png
    - assets/img/error.png


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
